# Generated by Django 4.2.5 on 2023-11-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.URLField(verbose_name="Facebook")),
                ("x", models.URLField(verbose_name="X Profile Link")),
                ("telegram", models.URLField(verbose_name="Telegram Link")),
                ("linkedIn", models.URLField(verbose_name="LinkedIn Profile")),
                ("whatsapp", models.URLField(verbose_name="WhatsApp Link")),
                ("phone", models.CharField(max_length=13, verbose_name="Phone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("email2", models.EmailField(max_length=254, verbose_name="Email")),
            ],
        ),
    ]
