# Generated by Django 4.2.5 on 2023-11-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("skills", models.CharField(max_length=50, verbose_name="Skills")),
                ("description", models.TextField(verbose_name="Description")),
                ("live", models.BooleanField(verbose_name="Live")),
                ("featured", models.BooleanField(verbose_name="Featured")),
                (
                    "image",
                    models.ImageField(upload_to="projects/", verbose_name="Image"),
                ),
                ("live_url", models.URLField(verbose_name="Url")),
                ("github_url", models.URLField(verbose_name="Github Link")),
                ("small_project", models.BooleanField(verbose_name="Small project")),
            ],
        ),
    ]
