# Generated by Django 4.2.5 on 2023-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_project_data_analysis_alter_project_live_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="data_analysis",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Data Analysis"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="live_url",
            field=models.URLField(blank=True, null=True, verbose_name="Url"),
        ),
    ]
