# Generated by Django 4.2.5 on 2023-11-16 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "institution",
                    models.CharField(max_length=50, verbose_name="Institute"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="certificates/", verbose_name="Image"),
                ),
                (
                    "file",
                    models.FileField(upload_to="files/", verbose_name="Upload File"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="skill",
            name="databases",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="frameworks",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="other",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="tools",
        ),
        migrations.AddField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_type",
            field=models.CharField(
                choices=[
                    ("language", "Language"),
                    ("framework", "Framework"),
                    ("databases", "Databases"),
                    ("tools", "Tools"),
                    ("other", "Other"),
                ],
                default="language",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="certificates",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="skills.certification",
                verbose_name="Certificates",
            ),
        ),
    ]
