# Generated by Django 4.2.5 on 2023-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0004_alter_skill_certificates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="skill_type",
            field=models.CharField(
                choices=[
                    ("Language", "Language"),
                    ("Framework", "Framework"),
                    ("Databases", "Databases"),
                    ("Tools", "Tools"),
                    ("Other", "Other"),
                ],
                default="language",
                max_length=50,
            ),
        ),
    ]
