# Generated by Django 4.2.5 on 2023-12-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0005_alter_skill_skill_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="skill_type",
            field=models.CharField(
                choices=[
                    ("Language", "Language"),
                    ("Framework", "Framework"),
                    ("Databases", "Databases"),
                    ("Tools", "Tools"),
                    ("Other", "Other"),
                ],
                default="Language",
                max_length=50,
            ),
        ),
    ]
